package pl.jo2.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.event.*;

public class AddOrEditBuddyDialog extends JDialog {
  private JPanel contentPane;
  private JButton buttonOK;
  private JButton buttonCancel;
  private JTextField textField1;
  private JTextField textField2;

  public AddOrEditBuddyDialog() {
    setContentPane(contentPane);
    setModal(true);
    getRootPane().setDefaultButton(buttonOK);

    buttonOK.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        onOK();
      }
    });

    buttonCancel.addActionListener(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        onCancel();
      }
    });

// call onCancel() when cross is clicked
    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    addWindowListener(new WindowAdapter() {
      public void windowClosing(WindowEvent e) {
        onCancel();
      }
    });

// call onCancel() on ESCAPE
    contentPane.registerKeyboardAction(new ActionListener() {
      public void actionPerformed(ActionEvent e) {
        onCancel();
      }
    }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
  }

  private void onOK() {
// add your code here
    dispose();
  }

  private void onCancel() {
// add your code here if necessary
    dispose();
  }

  public static void main(String[] args) {
    AddOrEditBuddyDialog dialog = new AddOrEditBuddyDialog();
    dialog.pack();
    dialog.setVisible(true);
    System.exit(0);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    contentPane = new JPanel();
    contentPane.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:noGrow", "center:max(d;4px):grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
    buttonOK = new JButton();
    buttonOK.setText("OK");
    CellConstraints cc = new CellConstraints();
    contentPane.add(buttonOK, cc.xy(5, 3));
    buttonCancel = new JButton();
    buttonCancel.setText("Cancel");
    contentPane.add(buttonCancel, cc.xy(3, 3));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
    contentPane.add(panel1, cc.xyw(1, 1, 5, CellConstraints.DEFAULT, CellConstraints.FILL));
    final JLabel label1 = new JLabel();
    label1.setText("Alias");
    panel1.add(label1, cc.xy(1, 1));
    textField1 = new JTextField();
    panel1.add(textField1, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
    final JLabel label2 = new JLabel();
    label2.setText("id");
    panel1.add(label2, cc.xy(1, 3));
    textField2 = new JTextField();
    panel1.add(textField2, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
    final JLabel label3 = new JLabel();
    label3.setText("");
    contentPane.add(label3, cc.xy(1, 3, CellConstraints.DEFAULT, CellConstraints.FILL));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return contentPane;
  }
}
