package pl.jo2.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by IntelliJ IDEA.
 * User: przemek
 * Date: 2009-10-30
 * Time: 21:41:11
 */
public class ChatPanel {
  private JPanel panel1;
  private JPanel messageLogPane;
  private JTextArea inputText;
  private JButton wyslijButton;
  private JToggleButton eToggleButton;
  private JButton wyczyscButton;

  public ChatPanel() {
    $$$setupUI$$$();
    wyslijButton.addActionListener(new ActionListener() {

      @Override
      public void actionPerformed(ActionEvent e) {
        if (!inputText.getText().trim().isEmpty()) {
          JLabel l = new JLabel();
          String label = "<html><b>ja:</b><br>" + inputText.getText().trim().replaceAll("\n", "<br>");
          l.setText(label);
          inputText.setText("");
          messageLogPane.add(l);
          messageLogPane.revalidate();
        }
      }
    });
  }

  private void createUIComponents() {
    messageLogPane = new JPanel();
    messageLogPane.setLayout(new BoxLayout(messageLogPane, BoxLayout.Y_AXIS));
    messageLogPane.setBorder(new EmptyBorder(1, 1, 1, 1));
  }

  public JPanel getMainPanel() {
    return panel1;
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    panel1 = new JPanel();
    panel1.setLayout(new BorderLayout(0, 0));
    final JSplitPane splitPane1 = new JSplitPane();
    splitPane1.setDividerLocation(100);
    splitPane1.setDividerSize(3);
    splitPane1.setOrientation(0);
    splitPane1.setResizeWeight(1.0);
    panel1.add(splitPane1, BorderLayout.CENTER);
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new FormLayout("fill:d:grow,left:0dlu:noGrow,fill:max(d;4px):noGrow,left:2dlu:noGrow,fill:max(d;4px):noGrow", "center:p:grow,top:0dlu:noGrow,center:max(d;4px):noGrow"));
    splitPane1.setRightComponent(panel2);
    wyslijButton = new JButton();
    wyslijButton.setText("wyslij");
    CellConstraints cc = new CellConstraints();
    panel2.add(wyslijButton, cc.xy(1, 3, CellConstraints.RIGHT, CellConstraints.DEFAULT));
    eToggleButton = new JToggleButton();
    eToggleButton.setText("E");
    panel2.add(eToggleButton, cc.xy(3, 3));
    wyczyscButton = new JButton();
    wyczyscButton.setText("wyczysc");
    panel2.add(wyczyscButton, cc.xy(5, 3));
    final JScrollPane scrollPane1 = new JScrollPane();
    panel2.add(scrollPane1, cc.xyw(1, 1, 5, CellConstraints.FILL, CellConstraints.FILL));
    inputText = new JTextArea();
    inputText.setRows(2);
    scrollPane1.setViewportView(inputText);
    final JPanel panel3 = new JPanel();
    panel3.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
    splitPane1.setLeftComponent(panel3);
    final JScrollPane scrollPane2 = new JScrollPane();
    panel3.add(scrollPane2, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
    scrollPane2.setViewportView(messageLogPane);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return panel1;
  }
}
